/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package datamonitoringcadet;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Administrator
 */
public class CadetView extends javax.swing.JPanel {

    /**
     * Creates new form CadetView
     */
    public CadetView() {
        initComponents();
        ulang();
        tampil_data();
    }
    
    Connection con = new Koneksi().getKoneksi();
    PreparedStatement pst;
    ResultSet rs;
    DefaultTableModel dtm;
    
        private void ulang(){
        buttonTambah.setVisible(true);
        buttonUbah.setVisible(true);
        buttonHapus.setVisible(true);
        textNIT.setText("");
        labelID.setText("");
        textNama.setText("");
        textAlamat.setText("");
        radioTeknik.setSelected(true);
    }
    
    private void tampil_data(){
        try {
            String[] judul = {"ID","NIT","NAMA LENGKAP","ALAMAT","PRODI","GOLDAR"};
            dtm = new DefaultTableModel(null, judul);
            tableCadet.setModel(dtm);
            String sql = "";
            if(textCari.getText().isEmpty()){
                sql = "select * from cadet";
            }else{
                sql = "select * from cadet where nama_lengkap like '%" + textCari.getText() +"%'";
            }
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            while(rs.next()){
                String[] data = {rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4), rs.getString(5), rs.getString(6)};
            dtm.addRow(data);
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonTutup = new javax.swing.JButton();
        textNama = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        textAlamat = new javax.swing.JTextField();
        textCari = new javax.swing.JTextField();
        comboGoldar = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableCadet = new javax.swing.JTable();
        radioKalk = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        labelID = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        buttonUbah = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        buttonHapus = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        buttonUlang = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        buttonTambah = new javax.swing.JButton();
        textNIT = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        radioTeknik = new javax.swing.JRadioButton();
        radioNautik = new javax.swing.JRadioButton();

        setBackground(new java.awt.Color(0, 102, 255));

        buttonTutup.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        buttonTutup.setText("TUTUP");
        buttonTutup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTutupActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setText("FORM DATA CADET");

        textCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textCariKeyReleased(evt);
            }
        });

        comboGoldar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "AB", "O", "B" }));

        tableCadet.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
            }
        ));
        tableCadet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableCadetMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableCadet);

        buttonGroup1.add(radioKalk);
        radioKalk.setText("Kalk");
        radioKalk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioKalkActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setText("NIT");

        labelID.setText("jLabel8");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setText("NAMA LENGKAP");

        buttonUbah.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        buttonUbah.setText("UBAH");
        buttonUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonUbahActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setText("ALAMAT");

        buttonHapus.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        buttonHapus.setText("HAPUS");
        buttonHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonHapusActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel6.setText("PRODI");

        buttonUlang.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        buttonUlang.setText("ULANG");
        buttonUlang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonUlangActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel7.setText("GOLDAR");

        buttonTambah.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        buttonTambah.setText("TAMBAH");
        buttonTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTambahActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setText("Cari Data Cadet Berdasarkan Nama");

        buttonGroup1.add(radioTeknik);
        radioTeknik.setText("Teknika");
        radioTeknik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioTeknikActionPerformed(evt);
            }
        });

        buttonGroup1.add(radioNautik);
        radioNautik.setText("Nautika");
        radioNautik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioNautikActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(textCari))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 636, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel7))
                                        .addGap(77, 77, 77)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(textAlamat)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(comboGoldar, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addGroup(layout.createSequentialGroup()
                                                                .addComponent(radioTeknik)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(radioNautik)))
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(radioKalk, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(69, 69, 69)
                                                        .addComponent(buttonHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(buttonUlang, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(0, 23, Short.MAX_VALUE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(textNIT, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(29, 29, 29)
                                                .addComponent(labelID)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE))
                                            .addComponent(textNama)))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(buttonTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonUbah, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(buttonTutup, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(440, 440, 440)
                        .addComponent(jLabel2)))
                .addContainerGap(211, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(textCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(textNIT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(labelID)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(textNama, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(textAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(radioTeknik)
                            .addComponent(radioNautik)
                            .addComponent(radioKalk))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(comboGoldar, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttonTambah)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(buttonUbah)
                                .addComponent(buttonHapus)
                                .addComponent(buttonUlang)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonTutup)))
                .addContainerGap(276, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonTutupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTutupActionPerformed
        // TODO add your handling code here:
        int index = HomeView.jTabbedPane3.getSelectedIndex();
        HomeView.jTabbedPane3.remove(index); 

    }//GEN-LAST:event_buttonTutupActionPerformed

    private void textCariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textCariKeyReleased
        // TODO add your handling code here:
        tampil_data();
    }//GEN-LAST:event_textCariKeyReleased

    private void tableCadetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableCadetMouseClicked
        // TODO add your handling code here:
        int row = tableCadet.getSelectedRow();
        labelID.setText(tableCadet.getValueAt(row, 0).toString());
        textNIT.setText(tableCadet.getValueAt(row, 1).toString());
        textNama.setText(tableCadet.getValueAt(row, 2).toString());
        textAlamat.setText(tableCadet.getValueAt(row, 3).toString());
        String prodi = tableCadet.getValueAt(row, 4).toString();
        if (prodi.equalsIgnoreCase("Teknika")){
            radioKalk.setSelected(true);
        }else{
           if(prodi.equalsIgnoreCase("Kalk")){
           radioNautik.setSelected(true);
        }else{
               radioTeknik.setSelected(true);
           }
        comboGoldar.setSelectedItem(tableCadet.getValueAt(row, 5).toString());
        buttonTambah.setEnabled(false);
        buttonUbah.setEnabled(true);
        buttonHapus.setEnabled(true);
        }
    }//GEN-LAST:event_tableCadetMouseClicked

    private void buttonUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonUbahActionPerformed
        // TODO add your handling code here:
        if(textNIT.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Inputan NPM Belum diisi");
            textNIT.requestFocus();
        }else if(textNama.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Inputan Nama Belum diisi");
            textNama.requestFocus();
        }else if(textAlamat.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Inputan Alamat Belum diisi");
            textAlamat.requestFocus();
        }else{
            ubah_data();
        }
    }//GEN-LAST:event_buttonUbahActionPerformed

    private void buttonHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonHapusActionPerformed
        // TODO add your handling code here:
        int konfirmasi = JOptionPane.showConfirmDialog(null,"Yakin Ingin Menghapus Data Ini?","Hapus Data?",0);
        if (konfirmasi == 0) {
            try {
                pst = con.prepareStatement("delete from cadet where id = ?");
                pst.setInt(1,Integer.parseInt(labelID.getText()));
                pst.executeUpdate();
                JOptionPane.showMessageDialog(null,"Data Cadet Berhasil dihapus");
                ulang();
                tampil_data();
            } catch (Exception e) {
                System.out.println(e.getMessage());
            }
        }
    }//GEN-LAST:event_buttonHapusActionPerformed

    private void buttonUlangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonUlangActionPerformed
        // TODO add your handling code here:
        ulang();
    }//GEN-LAST:event_buttonUlangActionPerformed

    private void buttonTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTambahActionPerformed
        // TODO add your handling code here:
        if(textNIT.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Inputan NPM Belum diisi");
            textNIT.requestFocus();
        }else if(textNama.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Inputan Nama Belum diisi");
            textNama.requestFocus();
        }else if(textAlamat.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Inputan Alamat Belum diisi");
            textAlamat.requestFocus();
        }else{
            tambah_data();
        }
    }//GEN-LAST:event_buttonTambahActionPerformed

    private void radioKalkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioKalkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioKalkActionPerformed

    private void radioTeknikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioTeknikActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioTeknikActionPerformed

    private void radioNautikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioNautikActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioNautikActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton buttonHapus;
    private javax.swing.JButton buttonTambah;
    private javax.swing.JButton buttonTutup;
    private javax.swing.JButton buttonUbah;
    private javax.swing.JButton buttonUlang;
    private javax.swing.JComboBox<String> comboGoldar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelID;
    private javax.swing.JRadioButton radioKalk;
    private javax.swing.JRadioButton radioNautik;
    private javax.swing.JRadioButton radioTeknik;
    private javax.swing.JTable tableCadet;
    private javax.swing.JTextField textAlamat;
    private javax.swing.JTextField textCari;
    private javax.swing.JTextField textNIT;
    private javax.swing.JTextField textNama;
    // End of variables declaration//GEN-END:variables
private void tambah_data() {
        try {
           String prodi = "Teknika";
           if(radioNautik.isSelected()){
               prodi = "Nautika";               
           }else{
               if(radioKalk.isSelected()){
                   prodi = "Kalk";
               }
           }
           pst = con.prepareStatement("insert into cadet values (?,?,?,?,?,?)");
           pst.setInt(1, 0);
           pst.setString(2, textNIT.getText());
           pst.setString(3, textNama.getText());
           pst.setString(4, textAlamat.getText());
           pst.setString(5, prodi);
           pst.setString(6, comboGoldar.getSelectedItem().toString());
           pst.executeUpdate();
           JOptionPane.showMessageDialog(null, "Data Cadet Berhasil ditambahkan");
           ulang();
           tampil_data();
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }

    private void ubah_data() {
        try {
           String prodi = "Teknika";
           if(radioNautik.isSelected()){
               prodi = "Nautika";               
           }else{
               if(radioKalk.isSelected()){
                   prodi = "Kalk";
               }
           }
           pst = con.prepareStatement("update cadet set nit=?, nama_lengkap=?, alamat=?, prodi=?, goldar=?, where id=?");
           pst.setString(1, textNIT.getText());
           pst.setString(2, textNama.getText());
           pst.setString(3, textAlamat.getText());
           pst.setString(4, prodi);
           pst.setString(5, comboGoldar.getSelectedItem().toString());
           pst.setInt(6, Integer.parseInt(labelID.getText()));
           pst.executeUpdate();
           JOptionPane.showMessageDialog(null, "Data berhasil diPerbaharui");
           ulang();
           tampil_data();
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }
}

