/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package datamonitoringcadet;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Administrator
 */
public class PemilihanView1 extends javax.swing.JPanel {

    /**
     * Creates new form PemilihanView1
     */
    public PemilihanView1() {
        initComponents();
                initComponents();
        tampil_tempat();
        ulang();
    }

    Connection con = new Koneksi().getKoneksi();
    PreparedStatement pst;
    ResultSet rs;
    DefaultTableModel dtm;
    String sql;
    
        private void ulang(){
        get_id_pemilihan();
        tanggalMulai.setDate(null);
        tanggalSelesai.setDate(null);
        comboTempat.setSelectedIndex(0);
        labelIDTempat.setText("");
        textAlamatPraktik.setText("");
        textNIT.setText("");
        textNama.setText("");
        textAlamat.setText("");
        textProdi.setText("");
        labelIDCadet.setText("");
        dtm = (DefaultTableModel)tabelCadet.getModel();
        dtm.setRowCount(0);
    }
        
        private void get_id_pemilihan(){
        try{
            pst = con.prepareStatement("select id_pemilihan from pemilihan_tempat order by id_pemilihan desc");
            rs = pst.executeQuery();
            if(rs.next()){
                int id = rs.getInt(1)+1;
                labelIDPemilihan.setText(id+"");
            }else{
                labelIDPemilihan.setText("1");
            }
        }catch (Exception e){
            System.out.println(e.getMessage());
        }
    }
    
    private void tampil_tempat(){
        try {
            comboTempat.addItem("Pilih tempat Praktik");
            pst = con.prepareStatement("select nama_tempat from tempat_praktek");
            rs = pst.executeQuery();
            while(rs.next()){
                comboTempat.addItem(rs.getString(1));
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        labelIDPemilihan = new javax.swing.JLabel();
        tanggalMulai = new com.toedter.calendar.JDateChooser();
        tanggalSelesai = new com.toedter.calendar.JDateChooser();
        comboTempat = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        textAlamatPraktik = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        textNIT = new javax.swing.JTextField();
        textNama = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        textAlamat = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        textProdi = new javax.swing.JTextField();
        buttonHapus = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelCadet = new javax.swing.JTable();
        ButtonTambah = new javax.swing.JButton();
        labelIDCadet = new javax.swing.JLabel();
        buttonUlang = new javax.swing.JButton();
        buttonSimpan = new javax.swing.JButton();
        labelIDTempat = new javax.swing.JLabel();
        buttonTutup1 = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Form Pemilihan Tempat Praktik");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setText("ID PEMILIHAN");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setText("TANGGAL MULAI");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setText("SELESAI");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setText("NAMA PERUSAHAAN");

        labelIDPemilihan.setText("jLabel6");

        comboTempat.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboTempatItemStateChanged(evt);
            }
        });
        comboTempat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboTempatActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel7.setText("ALAMAT PERUSAHAAN");

        textAlamatPraktik.setEditable(false);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel10.setText("NIT ");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel11.setText("NAMA LENGKAP");

        textNIT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textNITKeyPressed(evt);
            }
        });

        textNama.setEditable(false);

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel12.setText("ALAMAT");

        textAlamat.setEditable(false);

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel13.setText("PRODI");

        textProdi.setEditable(false);

        buttonHapus.setText("HAPUS");
        buttonHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonHapusActionPerformed(evt);
            }
        });

        tabelCadet.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID CADET", "NIT", "NAMA LENGKAP", "ALAMAT", "PRODI"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelCadet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelCadetMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelCadet);

        ButtonTambah.setText("TAMBAH");
        ButtonTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonTambahActionPerformed(evt);
            }
        });

        labelIDCadet.setText("jLabel6");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(buttonHapus)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane1)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel10)
                                .addComponent(jLabel11))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(textNIT, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(12, 12, 12)
                                    .addComponent(labelIDCadet))
                                .addComponent(textNama, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(34, 34, 34)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel12)
                                .addComponent(jLabel13))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(textProdi, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(ButtonTambah))
                                .addComponent(textAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel12)
                    .addComponent(textAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textNIT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelIDCadet))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(textNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(textProdi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonTambah))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonHapus)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        buttonUlang.setText("ULANG");
        buttonUlang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonUlangActionPerformed(evt);
            }
        });

        buttonSimpan.setText("SIMPAN");
        buttonSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSimpanActionPerformed(evt);
            }
        });

        labelIDTempat.setText("jLabel6");

        buttonTutup1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        buttonTutup1.setText("TUTUP");
        buttonTutup1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTutup1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(310, 310, 310)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(27, 27, 27)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(tanggalMulai, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                                            .addComponent(tanggalSelesai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel5))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(comboTempat, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(labelIDTempat))
                                            .addComponent(textAlamatPraktik, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(labelIDPemilihan)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(buttonTutup1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(buttonUlang)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(buttonSimpan))
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(108, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(labelIDPemilihan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(tanggalMulai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(tanggalSelesai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel7)
                                .addComponent(textAlamatPraktik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(comboTempat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labelIDTempat)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonUlang)
                    .addComponent(buttonSimpan)
                    .addComponent(buttonTutup1))
                .addContainerGap(103, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void comboTempatItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboTempatItemStateChanged
        // TODO add your handling code here:
        try {
            pst = con.prepareStatement("select * from tempat_praktek where nama_tempat=?");
            pst.setString(1, comboTempat.getSelectedItem().toString());
            rs = pst.executeQuery();
            if(rs.next()){
                textAlamatPraktik.setText(rs.getString(3));
                labelIDTempat.setText(rs.getString(1));
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_comboTempatItemStateChanged

    private void textNITKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textNITKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyChar() == 10){
            try {
                pst = con.prepareStatement("select * from cadet where nit=?");
                pst.setString(1, textNIT.getText());
                rs = pst.executeQuery();
                if(rs.next()){
                    labelIDCadet.setText(rs.getString(1));
                    textNama.setText(rs.getString(3));
                    textAlamat.setText(rs.getString(4));
                    textProdi.setText(rs.getString(5));
                }else{
                    JOptionPane.showMessageDialog(null, "NIT yang anda input tidak ditemukan!",
                        "Not Found", 0);
                    textNIT.setText("");
                    textNama.setText("");
                    textAlamat.setText("");
                    textProdi.setText("");
                    labelIDCadet.setText("");
                    textNIT.requestFocus();
                }
            } catch (Exception e) {
                System.out.println(e.getMessage());

            }
        }
    }//GEN-LAST:event_textNITKeyPressed

    private void buttonHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonHapusActionPerformed
        // TODO add your handling code here:
        int baris = tabelCadet.getSelectedRow();
        if(baris<0){
            JOptionPane.showMessageDialog(null, "Pilih dulu data mahasiswa yang ingin dihapus!",
                "Pilih Data", 0);
        }else{
            dtm.removeRow(baris);
        }
    }//GEN-LAST:event_buttonHapusActionPerformed

    private void tabelCadetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelCadetMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tabelCadetMouseClicked

    private void ButtonTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonTambahActionPerformed
        // TODO add your handling code here:
        if(labelIDCadet.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Data Cadet belum ditemukan!", "Gagal Tambah", 0);
        }else{
            String[] data = {labelIDCadet.getText(), textNIT.getText(), textNama.getText(),
                textAlamat.getText(), textProdi.getText()};
            dtm.addRow(data);
            textNIT.setText("");
            textNama.setText("");
            textAlamat.setText("");
            textProdi.setText("");
            labelIDCadet.setText("");
            textNIT.requestFocus();
        }
    }//GEN-LAST:event_ButtonTambahActionPerformed

    private void buttonUlangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonUlangActionPerformed
        // TODO add your handling code here:
        ulang();
    }//GEN-LAST:event_buttonUlangActionPerformed

    private void buttonSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSimpanActionPerformed
        // TODO add your handling code here:
        if(tanggalMulai.getDate()==null){
            JOptionPane.showMessageDialog(null, "Tanggal mulai belum dipilih!", "Pilih Tanggal", 0);
            tanggalMulai.requestFocus();
        }else if(tanggalSelesai.getDate()==null){
            JOptionPane.showMessageDialog(null, "Tanggal selesai belum dipilih!", "Pilih Tanggal", 0);
            tanggalSelesai.requestFocus();
        }else if(labelIDTempat.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Nama tempat PKL belum dipilih!", "Pilih Tempat PKL", 0);
            comboTempat.requestFocus();
        }else if(tabelCadet.getRowCount()<=0){
            JOptionPane.showMessageDialog(null, "Data mahasiswa belum ditambahkan!", "Pilih Tempat PKL", 0);
            textNIT.requestFocus();
        }else{
            try {
                simpan_pemilihan_tempat();
                simpan_pemilihan_detail();
                JOptionPane.showMessageDialog(null, "Data pemilihan tempat PKL berhasil disimpan");
                ulang();
            }catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Terjadi kesalahan pada simpan data: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_buttonSimpanActionPerformed

    private void buttonTutup1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTutup1ActionPerformed
        // TODO add your handling code here:
        int index = HomeView.jTabbedPane3.getSelectedIndex();
        HomeView.jTabbedPane3.remove(index);
    }//GEN-LAST:event_buttonTutup1ActionPerformed

    private void comboTempatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTempatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboTempatActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonTambah;
    private javax.swing.JButton buttonHapus;
    private javax.swing.JButton buttonSimpan;
    private javax.swing.JButton buttonTutup1;
    private javax.swing.JButton buttonUlang;
    private javax.swing.JComboBox<String> comboTempat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelIDCadet;
    private javax.swing.JLabel labelIDPemilihan;
    private javax.swing.JLabel labelIDTempat;
    private javax.swing.JTable tabelCadet;
    private com.toedter.calendar.JDateChooser tanggalMulai;
    private com.toedter.calendar.JDateChooser tanggalSelesai;
    private javax.swing.JTextField textAlamat;
    private javax.swing.JTextField textAlamatPraktik;
    private javax.swing.JTextField textNIT;
    private javax.swing.JTextField textNama;
    private javax.swing.JTextField textProdi;
    // End of variables declaration//GEN-END:variables
 private void simpan_pemilihan_detail() {
        try {
            int i=0;
            while(i<tabelCadet.getRowCount()){
                pst = con.prepareStatement("insert into pemilihan_detail (id_pemilihan, id) values (?, ?)");
                pst.setString(1, labelIDPemilihan.getText());
                pst.setString(2, tabelCadet.getValueAt(i, 0).toString());
                pst.executeUpdate();
                i++;
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }

    private void simpan_pemilihan_tempat() {
       try {
            SimpleDateFormat formatTanggal = new SimpleDateFormat("yyyy-MM-dd");
            pst = con.prepareStatement("insert into pemilihan_tempat values (?, ?, ?, ?)");
            pst.setString(1, labelIDPemilihan.getText());
            pst.setString(2, formatTanggal.format(tanggalMulai.getDate()));
            pst.setString(3, formatTanggal.format(tanggalSelesai.getDate()));
            pst.setString(4, labelIDTempat.getText());
            pst.executeUpdate();
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }
}
